# Generated by Django 5.1.1 on 2025-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
