# Generated by Django 5.1.1 on 2025-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0003_alter_userprofile_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
