# Generated by Django 5.1.1 on 2025-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0004_alter_userprofile_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='answer_1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
