# Generated by Django 5.1.1 on 2025-01-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0005_inspection_answer_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='answer_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='answer_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
