# Generated by Django 5.1.1 on 2025-01-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0006_inspection_answer_2_alter_inspection_answer_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='answer_2',
        ),
    ]
