# Generated by Django 5.1.1 on 2025-01-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0007_remove_inspection_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='question_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How is the curriculum being implemented, and how does it align with national standards?'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='question_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='What strategies are in place to ensure student engagement and learning outcomes?'),
        ),
    ]
