# Generated by Django 5.1.1 on 2025-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0008_alter_inspection_question_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='question_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How do teachers integrate technology into their lessons?'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='question_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How is student progress monitored and reported to parents?'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='question_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='How is discipline maintained in the school?'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='question_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Is there a policy in place for emergency situations?'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='question_7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="How are funds utilized to improve the school's quality?"),
        ),
    ]
